
package pl.grenczuk.walidatoridentyfikatorow;

import java.lang.String;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrzej Greńczuk
 * @version 1.0
 * @email andrzej.grenczuk@gmail.com
 * @email 158019@student.ue.wroc.pl
 */
public class WalidatorPesel extends javax.swing.JFrame {
 
   String autor = "Andrzej Greńczuk";
   String rok = "2022";
   String wersja = "1.0";
    int x;
    

    /**
     * Creates new form WalidatorIdentyfikatorow
     */
    public WalidatorPesel() {
        initComponents();
        impro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Waliduj = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Wyczyść = new javax.swing.JButton();
        Zamknij = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Plec = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DzienUrodzenia = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        MiesiacUrodzenia = new javax.swing.JLabel();
        RokUrodzenia = new javax.swing.JLabel();
        PESELNumber = new javax.swing.JTextField();
        WynikWalidacji = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LacznieSprawdzen = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("Walidator numeru PESEL");

        Waliduj.setText("Waliduj");
        Waliduj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WalidujActionPerformed(evt);
            }
        });

        jLabel2.setText("PESEL");

        Wyczyść.setText("Wyczyść");
        Wyczyść.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WyczyśćActionPerformed(evt);
            }
        });

        Zamknij.setText("Zamknij");
        Zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZamknijActionPerformed(evt);
            }
        });

        jLabel3.setText("Wynik");

        jLabel4.setText("Płeć");

        Plec.setText("jLabel5");

        jLabel6.setText("Dzień urodzenia");

        DzienUrodzenia.setText("jLabel7");

        jLabel8.setText("Miesiąc urodzenia");

        jLabel9.setText("Rok urodzenia");

        MiesiacUrodzenia.setText("jLabel10");

        RokUrodzenia.setText("jLabel11");

        PESELNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PESELNumberActionPerformed(evt);
            }
        });

        WynikWalidacji.setText("jLabel5");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pesel", "Wynik", "Płeć", "Dzień", "Miesiąc", "Rok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        LacznieSprawdzen.setText("jLabel5");

        jLabel7.setText("Łącznie sprawdzeń");

        jButton1.setText("Wyczyść historię");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Autor:");

        jLabel10.setText("Rok:");

        jLabel11.setText("Wersja:");

        jLabel12.setText("jLabel12");

        jLabel13.setText("jLabel13");

        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Waliduj)
                                        .addGap(18, 18, 18)
                                        .addComponent(Wyczyść)
                                        .addGap(18, 18, 18)
                                        .addComponent(Zamknij)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(WynikWalidacji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Plec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DzienUrodzenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(MiesiacUrodzenia, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                        .addComponent(RokUrodzenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(PESELNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(55, 55, 55)
                        .addComponent(LacznieSprawdzen)
                        .addGap(52, 52, 52)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(PESELNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(WynikWalidacji))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Plec))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(DzienUrodzenia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(MiesiacUrodzenia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(RokUrodzenia))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Waliduj)
                            .addComponent(Wyczyść)
                            .addComponent(Zamknij)
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LacznieSprawdzen)
                                    .addComponent(jLabel7))
                                .addGap(94, 94, 94))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    // WŁASNA METODA
    /*
    * Metoda zbiera wynik operacji weryfikacji numeru Pesel,
    * w tym rozbite dane cząstkowe i dokonuje ich wstawienia do tabeli
    */
    private void saveText() {
        String textField1Val = PESELNumber.getText();
        String textField2Val = WynikWalidacji.getText();
        String textField3Val = Plec.getText();
        String textField4Val = DzienUrodzenia.getText();
        String textField5Val = MiesiacUrodzenia.getText();
        String textField6Val = RokUrodzenia.getText();
        
        addRow(textField1Val,textField2Val,textField3Val,textField4Val,textField5Val,textField6Val);
    }
    // WŁASNA METODA
    /*
    * Metodat wstawia wynik walidacji do obiektu table -> jTable1
    */
    public void addRow(String str1, String str2, String str3, String str4, String str5, String str6){
        DefaultTableModel tabelModel = (DefaultTableModel) jTable1.getModel();
        tabelModel.addRow(new Object[]{str1, str2, str3, str4, str5, str6});
     }
    
    public void impro(){
               jLabel12.setText(autor);
               jLabel13.setText(rok);
               jLabel14.setText(wersja);
    }
    // WŁASNA METODA
    /*
    * Metoda oblicza ilość wprowadzonych wierszy
    */
    private void LiczWiersze(){
           LacznieSprawdzen.setText(Integer.toString(jTable1.getRowCount()));
    }
    
    private void WalidujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WalidujActionPerformed
        try {
            PeselValidator pv  = new PeselValidator(PESELNumber.getText());
            WynikWalidacji.setText(Boolean.toString(pv.isValid()));
            Plec.setText(pv.getSex());
            DzienUrodzenia.setText(Integer.toString(pv.getBirthDay()));
            MiesiacUrodzenia.setText(Integer.toString(pv.getBirthMonth()));
            RokUrodzenia.setText(Integer.toString(pv.getBirthYear()));
           saveText();
           LiczWiersze();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_WalidujActionPerformed

    private void WyczyśćActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WyczyśćActionPerformed
        PESELNumber.setText("");
        WynikWalidacji.setText("");
        Plec.setText("");
        DzienUrodzenia.setText("");
        MiesiacUrodzenia.setText("");
        RokUrodzenia.setText("");
    }//GEN-LAST:event_WyczyśćActionPerformed

    private void ZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZamknijActionPerformed
       System.exit(0);
    }//GEN-LAST:event_ZamknijActionPerformed

    private void PESELNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PESELNumberActionPerformed
        
    }//GEN-LAST:event_PESELNumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DefaultTableModel tabelModel = (DefaultTableModel) jTable1.getModel();
     for( int i =  jTable1.getRowCount() - 1; i >= 0; i-- )
        {
            tabelModel.removeRow(i);
            LacznieSprawdzen.setText("0");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WalidatorPesel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WalidatorPesel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WalidatorPesel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WalidatorPesel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new WalidatorPesel().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DzienUrodzenia;
    private javax.swing.JLabel LacznieSprawdzen;
    private javax.swing.JLabel MiesiacUrodzenia;
    private javax.swing.JTextField PESELNumber;
    private javax.swing.JLabel Plec;
    private javax.swing.JLabel RokUrodzenia;
    private javax.swing.JButton Waliduj;
    private javax.swing.JButton Wyczyść;
    private javax.swing.JLabel WynikWalidacji;
    private javax.swing.JButton Zamknij;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
